[pytest]

# Путь к папке с тестами
testpaths = tests

# Python path
pythonpath = . 

# Параметры запуска
addopts = 
    --showlocals
    --alluredir
    allure-results
    --allure-no-capture
    ; -v
    ; --html=reports/report.html
    ; --self-contained-html
    ; --alluredir=reports/allure_results
    ; -p no:cacheprovider

# Маркеры
markers =
    smoke: Smoke tests
    regression: Regression tests
    slow: Slow running tests